# Chapter 1. Getting Started with Tensorflow

## Declaring Tensors

### How to do it

#### 1. Fixed tensors 

In [34]:
import tensorflow as tf
import numpy as np

In [2]:
sess = tf.Session()

In [3]:
row_dim, col_dim = 4, 4
zero_tsr = tf.zeros([row_dim, col_dim])
print(sess.run(zero_tsr))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [4]:
ones_tsr = tf.ones([row_dim, col_dim])
print(sess.run(ones_tsr))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [5]:
filled_tsr = tf.fill([row_dim, col_dim], 42) # tf.constant(42, [row_dim, col_dim])
print(sess.run(filled_tsr))

[[42 42 42 42]
 [42 42 42 42]
 [42 42 42 42]
 [42 42 42 42]]


In [6]:
constant_tsr = tf.constant([1,2,3])
print(sess.run(constant_tsr))

[1 2 3]


#### 2. Tensors of similar shape

In [7]:
zerros_similar = tf.zeros_like(constant_tsr)
ones_similar = tf.ones_like(constant_tsr)
print(sess.run(ones_similar))

#### 3. Sequence tesors

In [8]:
linear_tsr = tf.linspace(start=0.0, stop=1.0, num=3)
sess.run(linear_tsr)

array([ 0. ,  0.5,  1. ], dtype=float32)

In [9]:
integer_seq_tsr = tf.range(start=6, limit=15, delta=3)
sess.run(integer_seq_tsr)

array([ 6,  9, 12], dtype=int32)

#### 4. Random tensors 

In [10]:
randunif_tsr = tf.random_uniform([row_dim, col_dim],minval=0, maxval=1)
sess.run(randunif_tsr)

array([[ 0.21577644,  0.26527762,  0.88894272,  0.8714534 ],
       [ 0.19649708,  0.05985546,  0.66370416,  0.67751098],
       [ 0.136657  ,  0.14989042,  0.25429702,  0.56260538],
       [ 0.21517289,  0.10973263,  0.92857814,  0.91596568]], dtype=float32)

In [11]:
randnorm_tsr = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
sess.run(randnorm_tsr)

array([[-0.50169104,  1.12910712, -0.17448488, -0.03084197],
       [ 0.54073656, -1.28030241,  0.25234702,  0.93611914],
       [ 0.30995876, -0.29518047,  1.40495825,  1.25791597],
       [-0.76784503, -0.76976031,  0.13693433,  1.08137488]], dtype=float32)

In [12]:
rancnorm_tsr = tf.truncated_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
sess.run(rancnorm_tsr)

array([[ 0.65750253,  0.81461048,  0.07964858, -0.05737245],
       [-0.69048303,  0.20637707,  1.53273737,  0.95230776],
       [ 0.5804311 , -0.11916508, -0.17622143, -0.89354736],
       [-0.07259462, -0.27899554, -0.95644695, -0.11555481]], dtype=float32)

In [13]:
shuffled_output = tf.random_shuffle(randnorm_tsr)
sess.run(shuffled_output)

array([[ -3.97951543e-01,  -8.87926877e-01,   1.36757565e+00,
          1.36720502e+00],
       [  3.92674021e-02,   1.52623284e+00,  -4.39403296e-01,
         -2.42043197e-01],
       [ -9.97536778e-02,   6.57862008e-01,  -1.45841396e+00,
          1.39034247e+00],
       [ -1.54029059e+00,   9.27746221e-02,   1.89941406e-04,
         -2.70091832e-01]], dtype=float32)

In [14]:
cropped_output = tf.random_crop(randnorm_tsr, [2,2])
sess.run(cropped_output)

array([[-0.90922922,  0.20341673],
       [-0.93583113,  0.43037504]], dtype=float32)

In [15]:
#cropped_image = tf.random_crop(my_image, [height/2, width/2, 3])

### How it works 

In [16]:
my_var = tf.Variable(tf.zeros([row_dim, col_dim]))
my_var

## Using Placeholders and Variables

### How to do it 

In [17]:
my_var = tf.Variable(tf.zeros([2,3]))
sess = tf.Session()
initialize_op = tf.global_variables_initializer()
sess.run(initialize_op)

In [18]:
sess = tf.Session()
x = tf.placeholder(tf.float32, shape=[2,2])
y = tf.identity(x)
x_vals = np.random.rand(2,2)
sess.run(y, feed_dict={x: x_vals})

array([[ 0.94429857,  0.20078321],
       [ 0.64561099,  0.00418309]], dtype=float32)

### There's more 

In [19]:
sess = tf.Session()
first_var = tf.Variable(tf.zeros([2,3]))
sess.run(first_var.initializer)
second_var = tf.Variable(tf.zeros_like(first_var))
sess.run(second_var.initializer)

## Working with Matrices

In [20]:
sess = tf.Session()

### How to do it 

#### 1. Creating matrices

In [21]:
identity_matrix = tf.diag([1.0, 1.0, 1.0])
A = tf.truncated_normal([2, 3])
B = tf.fill([2, 3], 5.0)
C = tf.random_uniform([3, 2])
D = tf.convert_to_tensor(np.array([[1., 2., 3.],[--3., -7., -1.],[0.,5.,-2.]]))
print(sess.run(identity_matrix))
print(sess.run(A))
print(sess.run(B))
print(sess.run(C))
print(sess.run(D))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.08817768 -1.29297519  1.73599327]
 [ 0.14553706  1.5034126   0.27617624]]
[[ 5.  5.  5.]
 [ 5.  5.  5.]]
[[ 0.30590749  0.9844588 ]
 [ 0.39202726  0.49616289]
 [ 0.29657638  0.84829605]]
[[ 1.  2.  3.]
 [ 3. -7. -1.]
 [ 0.  5. -2.]]


#### 2. Addition and subtraction uses the following function

In [22]:
print(sess.run(A+B))
print(sess.run(B-B))

[[ 3.92420292  3.61494064  4.32360125]
 [ 5.95105314  5.02008533  3.7089715 ]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [23]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


#### 3. Arguments of matmul()

In [24]:
help(tf.matmul)

Help on function matmul in module tensorflow.python.ops.math_ops:

matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)
    Multiplies matrix `a` by matrix `b`, producing `a` * `b`.
    
    The inputs must be matrices (or tensors of rank > 2, representing batches of
    matrices), with matching inner dimensions, possibly after transposition.
    
    Both matrices must be of the same type. The supported types are:
    `float16`, `float32`, `float64`, `int32`, `complex64`, `complex128`.
    
    Either matrix can be transposed or adjointed (conjugated and transposed) on
    the fly by setting one of the corresponding flag to `True`. These are `False`
    by default.
    
    If one or both of the matrices contain a lot of zeros, a more efficient
    multiplication algorithm can be used by setting the corresponding
    `a_is_sparse` or `b_is_sparse` flag to `True`. These are `False` by default.
    This opt

#### 4. Transpose the arguments as follows

In [25]:
print(sess.run(tf.transpose(C)))

[[ 0.55586839  0.40222096  0.10796094]
 [ 0.9706583   0.31836355  0.45144379]]


#### 5. Reinitializing gives us different values than before

#### 6. Determinant

In [26]:
print(sess.run(tf.matrix_determinant(D)))

76.0


#### 7. Decompositions

In [27]:
print(sess.run(tf.cholesky(identity_matrix)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 8. Eigenvalues and eigenvectors

In [28]:
print(sess.run(tf.self_adjoint_eig(D)))

(array([-10.65907521,  -0.22750691,   2.88658212]), array([[ 0.21749542,  0.63250104, -0.74339638],
       [-0.84526515, -0.2587998 , -0.46749277],
       [ 0.4880805 , -0.73004459, -0.47834331]]))


Eigenvalues in the first row and the subsequent vectors in the remaining vectors

## Declaring Operations 

In [29]:
sess = tf.Session()

In [30]:
print(sess.run(tf.add(A,B)))
print(sess.run(tf.subtract(A,B)))
print(sess.run(tf.matmul(B, identity_matrix)))
print(sess.run(tf.multiply(3,4)))
print(sess.run(tf.div(3,4)))
print(sess.run(tf.truediv(3,4)))
print(sess.run(tf.floordiv(3.0,4.0)))
print(sess.run(tf.mod(22.0,5.0)))
print(sess.run(tf.cross([1.,0.,0.],[0.,1.,0.])))
print(sess.run(tf.abs(-1.4)))
print(sess.run(tf.pow([2,3,4],2)))
print(sess.run(tf.square([2,3,4])))
print(sess.run(tf.sqrt([2.,3.,4.])))
print(sess.run(tf.negative([2,3,4])))
print(sess.run(tf.minimum([2,3,4],[1,5,2])))

[[ 4.56665897  3.9939878   4.95760393]
 [ 4.6289835   4.12478971  4.8843832 ]]
[[-4.46600199 -5.22288227 -4.85961676]
 [-3.99008894 -3.21788692 -3.96230078]]
[[ 5.  5.  5.]
 [ 5.  5.  5.]]
12
0
0.75
0.0
2.0
[ 0.  0.  1.]
1.4
[ 4  9 16]
[ 4  9 16]
[ 1.41421354  1.73205078  2.        ]
[-2 -3 -4]
[1 3 2]


In [31]:
print(sess.run(tf.erf(-0.1)))
print(sess.run(tf.squared_difference(4.,5.)))

-0.112463
1.0


### There's more

In [32]:
def custom_polynomial(value):
    return(tf.subtract(3 * tf.square(value),value)+10)
print(sess.run(custom_polynomial(11)))

362


## Implementing Activation Functions

### How to do it

In [36]:
print(sess.run(tf.nn.relu([-3., 3., 10.])))

[  0.   3.  10.]


In [37]:
print(sess.run(tf.nn.relu6([-3., 3., 10.])))

[ 0.  3.  6.]


In [38]:
print(sess.run(tf.nn.sigmoid([-1., 0., 1.])))

[ 0.26894143  0.5         0.7310586 ]


In [40]:
print(sess.run(tf.nn.tanh([-1., 0., 1.])))

[-0.76159418  0.          0.76159418]


In [41]:
print(sess.run(tf.nn.softsign([-1., 0., -1.])))

[-0.5  0.  -0.5]


In [42]:
print(sess.run(tf.nn.softplus([-1., 0., -1.])))

[ 0.31326166  0.69314718  0.31326166]


In [44]:
print(sess.run(tf.nn.elu([-1., 0., -1.])))

[-0.63212055  0.         -0.63212055]


## Working with Data Sources

### How to do it

#### 1. Iris data

In [52]:
from sklearn import datasets
iris = datasets.load_iris()
print(len(iris.data))

150


In [48]:
print(len(iris.target))

150


In [58]:
print(iris.target[0])

0


In [54]:
print(set(iris.target))

{0, 1, 2}


#### 2. Birth weight data

In [63]:
import requests 
birthdata_url = 'https://www.umass.edu/statdata/statdata/data/lowbwt.dat'
birth_file = requests.get(birthdata_url)
birth_data = birth_file.text.split('\r\n')[5:]
birth_header = [x for x in birth_data[0].split( '') if len(x)>=1]
birth_data = [[float(x) for x in y.split( '') if len(x)>=1] 
for y in birth_data[1:] if len(y)>=1]
print(len(birth_data))                                        

ValueError: empty separator

#### 3. Boston Housing data